# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='file.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\nfile.proto\"a\n\x04\x46ile\x12\x0c\n\x04\x44\x61ta\x18\x01 \x02(\t\x12\x19\n\x05Links\x18\x02 \x03(\x0b\x32\n.File.Link\x1a\x30\n\x04Link\x12\x0c\n\x04Hash\x18\x01 \x02(\t\x12\x0c\n\x04Name\x18\x02 \x02(\t\x12\x0c\n\x04Size\x18\x03 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FILE_LINK = _descriptor.Descriptor(
  name='Link',
  full_name='File.Link',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Hash', full_name='File.Link.Hash', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Name', full_name='File.Link.Name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Size', full_name='File.Link.Size', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=111,
)

_FILE = _descriptor.Descriptor(
  name='File',
  full_name='File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Data', full_name='File.Data', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Links', full_name='File.Links', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_FILE_LINK, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=111,
)

_FILE_LINK.containing_type = _FILE
_FILE.fields_by_name['Links'].message_type = _FILE_LINK
DESCRIPTOR.message_types_by_name['File'] = _FILE

File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), dict(

  Link = _reflection.GeneratedProtocolMessageType('Link', (_message.Message,), dict(
    DESCRIPTOR = _FILE_LINK,
    __module__ = 'file_pb2'
    # @@protoc_insertion_point(class_scope:File.Link)
    ))
  ,
  DESCRIPTOR = _FILE,
  __module__ = 'file_pb2'
  # @@protoc_insertion_point(class_scope:File)
  ))
_sym_db.RegisterMessage(File)
_sym_db.RegisterMessage(File.Link)


# @@protoc_insertion_point(module_scope)
