V1 = '1'
V2 = '2'
V3 = '3'
V4 = '4'
V5 = '5'
V6 = '6'
V7 = '7'
V8 = '8'
V9 = '9'

KNOWN_LEGACY_VERSIONS = {V1, V2, V3, V4, V5, V6}
# TODO: it *may* be a bug for V6 to be included in `KNOWN_USER_VERSIONS`
KNOWN_USER_VERSIONS = {V6, V7, V8, V9}

LATEST_VERSION = V9
LAST_NO_USER_CONFIG_VERSION = V6
FIRST_USER_CONFIG_VERSION = V7
